name: Release

on:  
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build"
        run: |
          zip -r TSBPack.zip . -i /home/runner/work/TSB-Bits/TSB-Bits/pack.png
         

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Resource Pack"
          files: |
            *.zip
