name: Release

on:  
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build"
        run: |
          pwd
          zip -r TSBPack.zip D:\a\TSB-Pack\
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Resource Pack"
          files: |
            *.zip
