name: Releases

#on: 
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:    
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        generateReleaseNotes: True
        tag: "latest"
        commit: "main"
        name: "Resource Pack"
        makeLatest: True
        token: ${{ secrets.GITHUB_TOKEN }}
