name: Create Archive
on: 
 workflow_dispatch:
 push:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'TSBPack.zip'
        exclusions: '*.git* *.github* */images/* *README.md*'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
       artifacts: "TSBPack.zip"
       token: ${{ secrets.GITHUB_TOKEN }}
       generateReleaseNotes: True
       commit: "main"
       name: "Resource Pack"
       makeLatest: True
       allowUpdates: True
