name: Create Archive
on: 
 workflow_dispatch:
 push:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: liudonghua123/delete-release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: 'Resource Pack'
    #- uses: dev-drprasad/delete-tag-and-release@v1.0
      #with:
       #tag_name: latest
       #github_token: ${{ secrets.GITHUB_TOKEN }}
       #delete_release: true
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'TSBPack.zip'
        exclusions: '*.git* *.github* */images/* *README.md*'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
       artifacts: "TSBPack.zip"
       token: ${{ secrets.GITHUB_TOKEN }}
       generateReleaseNotes: True
       commit: "main"
       name: "Resource Pack"
       makeLatest: True
       tag: "latest"
       allowUpdates: True
       omitBodyDuringUpdate: False
    
